# Generated by Django 2.1.1 on 2019-08-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=30, verbose_name='用户名')),
                ('photo', models.CharField(help_text='头像', max_length=1000, verbose_name='头像')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254, null=True, verbose_name='邮箱')),
                ('wallet_url', models.CharField(blank=True, help_text='钱包地址', max_length=300, null=True, verbose_name='钱包地址')),
                ('fri_code', models.CharField(blank=True, help_text='我的二维码地址（加好友）', max_length=300, null=True, verbose_name='我的二维码地址（加好友）')),
                ('pay_code', models.CharField(blank=True, help_text='收款二维码地址', max_length=300, null=True, verbose_name='收款二维码地址')),
                ('wbc_balance', models.DecimalField(blank=True, decimal_places=2, help_text='网博币余额', max_digits=10, null=True, verbose_name='网博币余额')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, help_text='支付密码', max_length=300, null=True, verbose_name='支付密码')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户支付密码表',
                'verbose_name_plural': '用户支付密码表',
                'db_table': 'user_pay',
            },
        ),
    ]
