# Generated by Django 2.1.1 on 2019-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telphone',
            field=models.EmailField(blank=True, help_text='手机号', max_length=254, null=True, verbose_name='手机号'),
        ),
    ]
