# Generated by Django 2.1.1 on 2019-08-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_user_wallet_url'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='订单号', max_length=64, null=True, verbose_name='订单号')),
                ('wbc_balance', models.DecimalField(decimal_places=2, help_text='网博币金额', max_digits=10, verbose_name='网博币金额')),
                ('pay_info', models.CharField(blank=True, help_text='付款说明', max_length=100, null=True, verbose_name='付款说明')),
                ('status', models.SmallIntegerField(choices=[(0, '收款'), (1, '付款'), (2, '转账')], default=0, help_text='付款方式', verbose_name='付款方式')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('friends', models.ForeignKey(blank=True, help_text='好友', null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.FriendApply', verbose_name='好友')),
                ('merchant', models.ForeignKey(blank=True, help_text='商家', null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.Merchant', verbose_name='商家')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '转账表',
                'verbose_name_plural': '转账表',
                'db_table': 'tran_account',
            },
        ),
    ]
