# Generated by Django 2.1.1 on 2019-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendapply',
            name='fri_code',
            field=models.CharField(blank=True, help_text='我的二维码地址（加好友）', max_length=300, null=True, verbose_name='我的二维码地址（加好友）'),
        ),
        migrations.AddField(
            model_name='friendapply',
            name='pay_code',
            field=models.CharField(blank=True, help_text='收款二维码地址', max_length=300, null=True, verbose_name='收款二维码地址'),
        ),
    ]
