# Generated by Django 2.1.1 on 2019-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20190806_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendapply',
            name='telphone',
            field=models.EmailField(blank=True, help_text='手机号', max_length=254, null=True, verbose_name='手机号'),
        ),
    ]
